keys:
  - &kube age1yuq8mumrg7yv2nxvfj3kzh6hxfjdl5zmsxda8pl5tjlvclmzjuns066uy2
  - &asus3 age17t4dzq2nsafpdvda9av2g04eumf4smm6g2u2hmh05urqzzdxeves39e0yy

creation_rules:
  # Encrypt all secrets to be used by SOPS operator
  - path_regex: ".*.sops.yaml"
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - *kube
          - *asus3
