apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackgres
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - sgconfigs.stackgres.io
      - sgclusters.stackgres.io
      - sginstanceprofiles.stackgres.io
      - sgpgconfigs.stackgres.io
      - sgpoolconfigs.stackgres.io
      - sgbackups.stackgres.io
      - sgbackupconfigs.stackgres.io
      - sgobjectstorages.stackgres.io
      - sgdbops.stackgres.io
      - sgdistributedlogs.stackgres.io
      - sgshardedclusters.stackgres.io
      - sgshardedbackups.stackgres.io
      - sgshardeddbops.stackgres.io
      - sgscripts.stackgres.io
      - sgstreams.stackgres.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
  - apiGroups:
      - admissionregistration.k8s.io
    resourceNames:
      - stackgres
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - sgconfigs.stackgres.io
      - sgclusters.stackgres.io
      - sginstanceprofiles.stackgres.io
      - sgpgconfigs.stackgres.io
      - sgpoolconfigs.stackgres.io
      - sgbackups.stackgres.io
      - sgbackupconfigs.stackgres.io
      - sgobjectstorages.stackgres.io
      - sgdbops.stackgres.io
      - sgdistributedlogs.stackgres.io
      - sgshardedclusters.stackgres.io
      - sgshardedbackups.stackgres.io
      - sgshardeddbops.stackgres.io
      - sgscripts.stackgres.io
      - sgstreams.stackgres.io
    resources:
      - customresourcedefinitions
    verbs:
      - patch
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - prometheuses.monitoring.coreos.com
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - ""
      - apps
      - extensions
      - rbac.authorization.k8s.io
      - batch
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
      - endpoints
      - endpoints/restricted
      - persistentvolumeclaims
      - configmaps
      - secrets
      - deployments
      - statefulsets
      - serviceaccounts
      - namespaces
      - roles
      - rolebindings
      - events
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
      - deletecollection
      - patch
  - apiGroups:
      - stackgres.io
    resources:
      - sgclusters
      - sgpgconfigs
      - sginstanceprofiles
      - sgpoolconfigs
      - sgbackupconfigs
      - sgbackups
      - sgdistributedlogs
      - sgdbops
      - sgobjectstorages
      - sgscripts
      - sgshardedclusters
      - sgshardedbackups
      - sgshardeddbops
      - sgstreams
      - sgconfigs
    verbs:
      - create
      - watch
      - list
      - get
      - update
      - patch
      - delete
  - apiGroups:
      - stackgres.io
    resources:
      - sgconfigs/status
      - sgclusters/status
      - sgdistributedlogs/status
      - sgclusters/finalizers
      - sgpgconfigs/finalizers
      - sginstanceprofiles/finalizers
      - sgpoolconfigs/finalizers
      - sgbackupconfigs/finalizers
      - sgbackups/finalizers
      - sgdistributedlogs/finalizers
      - sgdbops/finalizers
      - sgobjectstorages/finalizers
      - sgscripts/finalizers
      - sgshardedclusters/finalizers
      - sgshardedbackups/finalizers
      - sgshardeddbops/finalizers
      - sgstreams/finalizers
      - sgconfigs/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
      - apps
      - batch
    resources:
      - statefulsets/finalizers
      - persistentvolumeclaims/finalizers
      - deployments/finalizers
      - services/finalizers
      - endpoints/finalizers
      - cronjobs/finalizers
      - jobs/finalizers
      - pods/finalizers
    verbs:
      - update
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - list
      - get
      - watch
      - create
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
    verbs:
      - list
      - get
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheus
      - prometheuses
      - podmonitors
    verbs:
      - list
      - get
  - apiGroups:
      - shardingsphere.apache.org
    resources:
      - computenodes
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
      - patch
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
      - triggerauthentications
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
      - patch
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
      - patch
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
      - patch
