apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "10"
  labels:
    app: stackgres-operator-init
    job: install-sgconfig
  name: stackgres-install-sgconfig
  namespace: stackgres
spec:
  template:
    metadata:
      labels:
        app: stackgres-operator-init
        job: install-sgconfig
    spec:
      containers:
        - command:
            - /bin/bash
            - -ecx
            - |
              kubectl replace -f /SGConfig.yaml
              RETRY=10
              while true
              do
                if kubectl apply -f /sgconfig.json
                then
                  break
                else
                  if [ "$RETRY" -le 0 ]
                  then
                    exit 1
                  fi
                  RETRY="$((RETRY - 1))"
                  sleep 2
                fi
              done
          image: quay.io/ongres/kubectl:v1.31.3-build-6.38
          imagePullPolicy: IfNotPresent
          name: install-sgconfig
          volumeMounts:
            - mountPath: /SGConfig.yaml
              name: sgconfig-crd
              subPath: SGConfig.yaml
            - mountPath: /sgconfig.json
              name: sgconfig
              subPath: sgconfig.json
      restartPolicy: OnFailure
      serviceAccountName: stackgres-init
      terminationGracePeriodSeconds: 0
      volumes:
        - configMap:
            name: stackgres-sgconfig-crd
            optional: false
          name: sgconfig-crd
        - configMap:
            name: stackgres-sgconfig
            optional: false
          name: sgconfig
  ttlSecondsAfterFinished: 3600
