apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: argocd
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: argocd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 443
# ${pkgs.kubectl}/bin/kubectl port-forward svc/argocd-server -n argocd 8080:443 --address $IP --address 127.0.0.1
