apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: superset
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/dev/superset
    repoURL: https://github.com/arnarg/nixidy-demo.git
    targetRevision: main
  syncPolicy: {}
