apiVersion: v1
kind: Service
metadata:
  name: temporal-grpc
  namespace: temporal
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: frontend
  ports:
    - name: grpc
      protocol: TCP
      port: 7233
      targetPort: 7233

---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: temporal
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: frontend
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: temporal-tailscale
#   namespace: temporal
#   annotations:
#     tailscale.com/tags: "tag:k8s"
#     # tailscale.com/funnel: "true"
# spec:
#   ingressClassName: tailscale
#   rules:
#     # n8n.taila1b08a.ts.net
#     - host: temporal-ui.taila1b08a.ts.net
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: temporal-web
#                 port:
#                   number: 8080
# - host: temporal-grpc.taila1b08a.ts.net
#   http:
#     paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: temporal-frontend
#             port:
#               number: 7233
