apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: superset-worker
    chart: superset-0.15.0
    heritage: Helm
    release: superset
  name: superset-worker
  namespace: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset-worker
      release: superset
  template:
    metadata:
      annotations:
        checksum/configOverrides: 374f6ae337f58b0fd2acd61c95bb6cfc187c1dad030120b02386cd735026b18f
        checksum/configOverridesFiles: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        checksum/connections: 2d41a2c51ec2fc809be84fc0ea0e603c946d529b4a0e43f7257e617909561a75
        checksum/extraConfigs: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        checksum/extraSecretEnv: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        checksum/extraSecrets: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        checksum/superset_bootstrap.sh: 0d52e3d9174281b059ca768051bb4a84e415e610b416e1466fdb394112387340
        checksum/superset_config.py: f57653490c768512c783bbc7312302d5a18278e70d2099ee7d8dc756a627a4c4
      labels:
        app: superset-worker
        release: superset
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - . /app/pythonpath/superset_bootstrap.sh; celery --app=superset.tasks.celery_app:app worker
          env:
            - name: SUPERSET_PORT
              value: "8088"
          envFrom:
            - secretRef:
                name: superset-env
          image: apachesuperset.docker.scarf.sh/apache/superset:5.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - celery -A superset.tasks.celery_app:app inspect ping -d celery@$HOSTNAME
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
          name: superset
          resources: {}
          volumeMounts:
            - mountPath: /app/pythonpath
              name: superset-config
              readOnly: true
      initContainers:
        - command:
            - /bin/sh
            - -c
            - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -wait "tcp://$REDIS_HOST:$REDIS_PORT" -timeout 120s
          envFrom:
            - secretRef:
                name: superset-env
          image: apache/superset:dockerize
          imagePullPolicy: IfNotPresent
          name: wait-for-postgres-redis
      securityContext:
        runAsUser: 0
      volumes:
        - name: superset-config
          secret:
            secretName: superset-config
