apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app: superset
    chart: superset-0.15.0
    heritage: Helm
    release: superset
  name: superset-init-db
  namespace: superset
spec:
  template:
    metadata:
      name: superset-init-db
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - . /app/pythonpath/superset_bootstrap.sh; . /app/pythonpath/superset_init.sh
          envFrom:
            - secretRef:
                name: superset-env
          image: apachesuperset.docker.scarf.sh/apache/superset:5.0.0
          imagePullPolicy: IfNotPresent
          name: superset-init-db
          resources: {}
          volumeMounts:
            - mountPath: /app/pythonpath
              name: superset-config
              readOnly: true
      initContainers:
        - command:
            - /bin/sh
            - -c
            - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -timeout 120s
          envFrom:
            - secretRef:
                name: superset-env
          image: apache/superset:dockerize
          imagePullPolicy: IfNotPresent
          name: wait-for-postgres
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      volumes:
        - name: superset-config
          secret:
            secretName: superset-config
