apiVersion: v1
kind: Secret
metadata:
  labels:
    app: superset
    chart: superset-0.15.0
    heritage: Helm
    release: superset
  name: superset-config
  namespace: superset
stringData:
  superset_bootstrap.sh: "bootstrapScript: |\n  #!/bin/bash\n  \n  # Install system-level dependencies\n  apt-get update && apt-get install -y \\\n    python3-dev \\\n    default-libmysqlclient-dev \\\n    build-essential \\\n    pkg-config\n\n  # Install required Python packages\n  uv pip install \\\n    authlib \\\n    psycopg2-binary \\\n    mysqlclient \\\n    pymssql \\\n\n  # Create bootstrap file if it doesn't exist\n  if [ ! -f ~/bootstrap ]; then\n    echo \"Running Superset with uid 0\" > ~/bootstrap\n  fi\n"
  superset_config.py: |2

    import os
    from flask_caching.backends.rediscache import RedisCache

    def env(key, default=None):
        return os.getenv(key, default)

    # Redis Base URL
    REDIS_BASE_URL=f"{env('REDIS_PROTO')}://{env('REDIS_HOST')}:{env('REDIS_PORT')}"

    # Redis URL Params
    REDIS_URL_PARAMS = ""

    # Build Redis URLs
    CACHE_REDIS_URL = f"{REDIS_BASE_URL}/{env('REDIS_DB', 1)}{REDIS_URL_PARAMS}"
    CELERY_REDIS_URL = f"{REDIS_BASE_URL}/{env('REDIS_CELERY_DB', 0)}{REDIS_URL_PARAMS}"

    MAPBOX_API_KEY = env('MAPBOX_API_KEY', '')
    CACHE_CONFIG = {
          'CACHE_TYPE': 'RedisCache',
          'CACHE_DEFAULT_TIMEOUT': 300,
          'CACHE_KEY_PREFIX': 'superset_',
          'CACHE_REDIS_URL': CACHE_REDIS_URL,
    }
    DATA_CACHE_CONFIG = CACHE_CONFIG

    SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{env('DB_USER')}:{env('DB_PASS')}@{env('DB_HOST')}:{env('DB_PORT')}/{env('DB_NAME')}"
    SQLALCHEMY_TRACK_MODIFICATIONS = True

    class CeleryConfig:
      imports  = ("superset.sql_lab", )
      broker_url = CELERY_REDIS_URL
      result_backend = CELERY_REDIS_URL

    CELERY_CONFIG = CeleryConfig
    RESULTS_BACKEND = RedisCache(
          host=env('REDIS_HOST'),
          port=env('REDIS_PORT'),
          key_prefix='superset_results',
    )
  superset_init.sh: |
    #!/bin/sh
    set -eu
    echo "Upgrading DB schema..."
    superset db upgrade
    echo "Initializing roles..."
    superset init

    echo "Creating admin user..."
    superset fab create-admin \
                    --username admin \
                    --firstname Superset \
                    --lastname Admin \
                    --email admin@superset.com \
                    --password admin \
                    || true

    if [ -f "/app/configs/import_datasources.yaml" ]; then
      echo "Importing database connections.... "
      superset import_datasources -p /app/configs/import_datasources.yaml
    fi
type: Opaque
