apiVersion: v1
data:
  password: c3VwZXJzZXQ=
  postgres-password: UHg4bEJ1dVpVOQ==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: superset
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.1.0
    helm.sh/chart: postgresql-13.4.4
  name: superset-postgresql
  namespace: superset
type: Opaque
