apiVersion: v1
kind: Service
metadata:
  labels:
    app: superset
    chart: superset-0.15.0
    heritage: Helm
    release: superset
  name: superset
  namespace: superset
spec:
  ports:
    - name: http
      nodePort: 30088
      port: 8088
      protocol: TCP
      targetPort: http
  selector:
    app: superset
    release: superset
  type: NodePort
