apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    app: superset
    chart: superset-0.15.0
    heritage: Helm
    release: superset
  name: superset-env
  namespace: superset
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQmNheTc0NHUxUVRNQlA2
        MmVyTFpXRnR0NFZlU0RkWVljMjlzbFIzMVJ3CkZobkFEUWJPY0daZHlTa2NZUFNT
        T2doR0lTd3EzM0Y0eGQ3Y3lNTlB6RzAKLS0tIDdldGkwRGhQcGpoSEJlcDZGWnpJ
        WlAyOFUyeUtSaThWNWpiS3YrZmExdUUKoPvkKtjg3bnSmZ6ZT80njALTBAQhGrzp
        4Ptqcc1g6D0ObXrMJCTRnZGezebaC9/GMBZU0WYL8/MNYBbkexDg8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yuq8mumrg7yv2nxvfj3kzh6hxfjdl5zmsxda8pl5tjlvclmzjuns066uy2
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRzI2TFBUcGtlSjY4N0h2
        SHVyT09TL2w3REQrVEo1SkwwcjR6bXh2TnpFClNGUWhIcCtmb1RLVWw5REZFMjhi
        aUlua1U0QWZUZFpRTXMxdmdhNDNLbVEKLS0tIENKOGdyTGNjNzZoaXFlUnBzeUZJ
        SmkrRGEzTFFQTWV3RDJCVjVXdGNuSXcKlJXtt6aKFv/RzoWP6iXQ5ukqNm6iBIq1
        asYKJR59RTD0C98bWnXyYHFT8NeCWr8dMrCu9fJz/BK83YxeHm3uXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17t4dzq2nsafpdvda9av2g04eumf4smm6g2u2hmh05urqzzdxeves39e0yy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-16T19:35:57Z"
  mac: ENC[AES256_GCM,data:mFB7f99kOhU3NhWTIJf096DBdGVUNqcQ/JKjGV96oczPr8qhTlI10Vf7oaV95R0eOGYb8p/mD//KLF4VsVDwy+zJnkIW0UaH4InDx+3t+8rHhtQ+meUq41qg12ndGpIU+8Lm73bN96xA6Vn/TxURioH7CajVM5MKzQqCFuxXl1A=,iv:gVZD/jQx/M1pcECcG6eaD1uraOKQwev1XuMmhMJhUtY=,tag:DY3vUkd6BFhE+3AcjFrlRQ==,type:str]
  version: 3.10.2
spec:
  secretTemplates:
    - name: superset-env
      stringData:
        DB_HOST: ENC[AES256_GCM,data:srRVykQHsWRzKNJhEcTbit2YbA==,iv:OKbhEp7tVxxc3x1o21//K2nPPQRMXuSU3V3w6t3HB5Y=,tag:9A4osXRCOjhyJEIE+eDYHA==,type:str]
        DB_NAME: ENC[AES256_GCM,data:9zRLMvJpBKM=,iv:UtCuZ/QyECu0P2n/B2VU8GTHtnWI0bhAAPzwaDlo5HY=,tag:dNZ/KXM7HCUom0Rrb6NVyw==,type:str]
        DB_PASS: ENC[AES256_GCM,data:nqNoE9w1BAM=,iv:Is8YwjbI+fUhrezB5iefax/rVebbtex7GwzHYmDqe0Q=,tag:K+8jHXo2HpBsO9nWD7TJJQ==,type:str]
        DB_PORT: ENC[AES256_GCM,data:RhA84g==,iv:Z0wDGAGHMGvR3RQ8ExOA2618VFqw+LqX7YfJ/oxJZxI=,tag:zZ3jdBK/Q2eTMn1fl5HApw==,type:str]
        DB_USER: ENC[AES256_GCM,data:XaUqHGI2oek=,iv:SxB6HPpgWWR+j3t0OQH7EWsuBllw9rfvr1YVqqHZBGY=,tag:GrqpG0jW3q4Ncd4PYFocPQ==,type:str]
        REDIS_CELERY_DB: ENC[AES256_GCM,data:pQ==,iv:wVUbuptISU0RjOBm7LgatYrIG4OlfW1qk6mmuNaJ5uU=,tag:fVwq0vJXl6zirXnSJxJ/QA==,type:str]
        REDIS_DB: ENC[AES256_GCM,data:Zw==,iv:v+iBGjxKYgJiNRRFfahWdzsxcZldAfaec74ETgLD63g=,tag:c5Wm1gtEngOwuAThwqtSAw==,type:str]
        REDIS_HOST: ENC[AES256_GCM,data:3EcFHiJjE/SWu9jR4LXcMGKzg8qIBaQ=,iv:g5mS1rnIrgCmLP8GEcBMgonZIu81fjdt+CI+XBvAdaw=,tag:ZqK1TSo3+nxAD44997OhAg==,type:str]
        REDIS_PORT: ENC[AES256_GCM,data:JSdMpg==,iv:mCDKolLWnYyekPPnFgLc8ITlV7GLStYkSZwpVGmLr8U=,tag:xQXBvVn0m2jm1jucfP3xSw==,type:str]
        REDIS_PROTO: ENC[AES256_GCM,data:hUYz3gQ=,iv:KSJqPPJcx7mlSTs82sBWqzliPr+tc2hPpK+jMonaqoo=,tag:kg45sxXYp9BznyqYJtQUag==,type:str]
        REDIS_USER: ""
        SUPERSET_SECRET_KEY: ENC[AES256_GCM,data:OcaGTcvqyPHF582smr6lgbOMg8S5dhY/3aE03RaLv5fnJpE7lepm8rFgAhsfxwYcHn/btHJCxK9xlCHmH6Q=,iv:ZBm5HCSPjrhIL9EY6QSQXlwRqxEMCXlWvBiEZe36CPA=,tag:tvFrFkxtrO/WxkCaTmDRrA==,type:str]
type: Opaque
