apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flink-operator-serving-cert
  namespace: flink
spec:
  commonName: FlinkDeployment Validator
  dnsNames:
    - flink-operator-webhook-service.flink.svc
    - flink-operator-webhook-service.flink.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: flink-operator-selfsigned-issuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: flink-operator-webhook-secret
  secretName: webhook-server-cert
