apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: 1.13.0
    helm.sh/chart: flink-kubernetes-operator-1.13.0
  name: flink-operator-role-binding
  namespace: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-operator
subjects:
  - kind: ServiceAccount
    name: flink-operator
    namespace: flink
