apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    chart: airflow-1.18.0
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-pod-log-reader-rolebinding
  namespace: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-pod-log-reader-role
subjects:
  - kind: ServiceAccount
    name: airflow-api-server
    namespace: airflow
  - kind: ServiceAccount
    name: airflow-triggerer
    namespace: airflow
