apiVersion: v1
data:
  password: YTFYRUhSRlI1Vg==
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    chart: airflow-1.18.0
    component: redis
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-redis-password
  namespace: airflow
type: Opaque
