apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    chart: airflow-1.18.0
    component: dag-processor
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-dag-processor
  namespace: airflow
