apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    chart: airflow-1.18.0
    component: api-server
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-api-server
  namespace: airflow
