apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    chart: airflow-1.18.0
    component: scheduler
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-scheduler
  namespace: airflow
