apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    chart: airflow-1.18.0
    component: create-user-job
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-create-user-job
  namespace: airflow
