apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-starrocks-operator
  name: kube-starrocks-operator
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - serviceaccounts
      - services
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - starrocks.com
    resources:
      - starrocksclusters
      - starrockswarehouses
    verbs:
      - '*'
  - apiGroups:
      - starrocks.com
    resources:
      - starrocksclusters/finalizers
      - starrockswarehouses/finalizers
    verbs:
      - update
  - apiGroups:
      - starrocks.com
    resources:
      - starrocksclusters/status
      - starrockswarehouses/status
    verbs:
      - get
      - patch
      - update
