apiVersion: v1
data:
  be.conf: |
    be_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060
    sys_log_level = INFO
    default_rowset_type = beta
kind: ConfigMap
metadata:
  labels:
    app: be
    cluster: kube-starrocks
  name: kube-starrocks-be-cm
  namespace: starrocks
