apiVersion: v1
data:
  fe.conf: |
    LOG_DIR = ${STARROCKS_HOME}/log
    DATE = "$(date +%Y%m%d-%H%M%S)"
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseG1GC -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"
    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010
    mysql_service_nio_enabled = true
    sys_log_level = INFO
    # When shutting down FE, it will wait for min_graceful_exit_time_second seconds before refusing new requests. If you
    # want to ensure that queries, writes, and other operations complete smoothly, you need to ensure that the time it
    # takes for the Pod to become Not Ready is less than min_graceful_exit_time_second. The default Pod configuration is
    # probe.FailureThreshold = 3, probe.PeriodSeconds = 5, so in the worst case, the Pod will have (3+1)*5 = 20s to
    # transition to Node Not Ready state. Since the default value of min_graceful_exit_time_second is 15, we change it to a larger value.
    # Note: StarRocks version must be greater than or equal to 3.4.2 to support this configuration, otherwise it will not take effect.
    min_graceful_exit_time_second = 25
kind: ConfigMap
metadata:
  labels:
    app: fe
    cluster: kube-starrocks
  name: kube-starrocks-fe-cm
  namespace: starrocks
