apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cn-leader-election-rolebinding
  namespace: starrocks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cn-leader-election-role
subjects:
  - kind: ServiceAccount
    name: starrocks
    namespace: starrocks
