apiVersion: v1
data:
  N8N_LOG_LEVEL: info
  N8N_LOG_OUTPUT: console
kind: ConfigMap
metadata:
  labels:
    app: n8n
    chart: n8n-1.14.3
    heritage: Helm
    release: n8n
  name: n8n-logging-configmap
  namespace: metallb
