apiVersion: v1
data:
  secretkey: dXB6UVVkc1JLQWhRM0hTdGg3aHZybThuVFJBbEN4d0xrVUdlVlVJeFZScTdJa3FCOGQzbTVGRlk5enl0dE83SzhHWURDWVMxUmU1OG5mZXlsU0F3OGg4czJreUdMS3VhZVBoOHBkN3Z1M090bU0zbnhsYkQzc3dxd2pjcGZOWkZDSm9tNW9Uakw2WUdjdThrd3JkUWdGTVp1YW84VmVRakVnek92dVhqam1zMmF6ZHh6bDFleE9FYlhOVlFrOTZnNmVhNGdpOUpHSWdpcVlrN1ViaTc1S2xYakNETm1tTXN3bkVjV1M1RnQ4d1ZkdTVKYjhiallrenJMc0hiSVN2dw==
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: speaker
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    app.kubernetes.io/version: 0.15.2
    helm.sh/chart: metallb-6.4.22
  name: metallb-memberlist
  namespace: metallb
