apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: druid
    chart: druid-31.0.5
    component: broker
    heritage: Helm
    release: druid
  name: druid-broker
  namespace: druid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid
      component: broker
      release: druid
  template:
    metadata:
      annotations:
        druid.k8s.enablePatching: "true"
      labels:
        app: druid
        component: broker
        release: druid
    spec:
      containers:
        - args:
            - broker
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DRUID_MAXDIRECTMEMORYSIZE
              value: 400m
            - name: DRUID_XMS
              value: 512m
            - name: DRUID_XMX
              value: 512m
            - name: druid_processing_buffer_sizeBytes
              value: "50000000"
            - name: druid_processing_numMergeBuffers
              value: "2"
            - name: druid_processing_numThreads
              value: "1"
          envFrom:
            - configMapRef:
                name: druid
          image: apache/druid:30.0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /status/health
              port: 8082
            initialDelaySeconds: 60
          name: druid
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /status/health
              port: 8082
            initialDelaySeconds: 60
          resources: {}
      serviceAccountName: druid-broker
