apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: druid
    chart: druid-31.0.5
    component: overlord
    heritage: Helm
    release: druid
  name: druid-overlord
  namespace: druid
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - pods/log
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
