apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: druid
    chart: druid-31.0.5
    component: broker
    heritage: Helm
    release: druid
  name: druid-broker
  namespace: druid
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - '*'
