apiVersion: v1
kind: Service
metadata:
  labels:
    app: druid
    chart: druid-31.0.5
    component: middle-manager
    heritage: Helm
    release: druid
  name: druid-middle-manager
  namespace: druid
spec:
  ports:
    - name: http
      port: 8091
      protocol: TCP
      targetPort: http
  selector:
    app: druid
    component: middle-manager
    release: druid
  type: ClusterIP
