apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: druid
    chart: druid-31.0.5
    component: middle-manager
    heritage: Helm
    release: druid
  name: druid-middle-manager
  namespace: druid
