apiVersion: v1
kind: Service
metadata:
  labels:
    app: druid
    chart: druid-31.0.5
    component: historical
    heritage: Helm
    release: druid
  name: druid-historical
  namespace: druid
spec:
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: http
  selector:
    app: druid
    component: historical
    release: druid
  type: ClusterIP
