apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
  name: tailscale
  namespace: druid
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: druid
