apiVersion: v1
kind: Service
metadata:
  labels:
    app: druid
    chart: druid-31.0.5
    component: overlord
    heritage: Helm
    release: druid
  name: druid-overlord
  namespace: druid
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: http
  selector:
    app: druid
    component: overlord
    release: druid
  type: ClusterIP
