apiVersion: v1
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: true
      folder: ""
      name: default
      options:
        path: /var/lib/grafana/dashboards/default
      orgId: 1
      type: file
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: TemporalMetrics
      type: prometheus
      url: http://temporalio-prometheus-server
  download_dashboards.sh: "#!/usr/bin/env sh\nset -euf\nmkdir -p /var/lib/grafana/dashboards/default\n\ncurl -skf \\\n--connect-timeout 60 \\\n--max-time 60 \\\n-H \"Accept: application/json\" \\\n-H \"Content-Type: application/json;charset=UTF-8\" \\\n  \"https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/advanced-visibility-specific.json\" \\\n  | sed '/-- .* --/! s/\"datasource\":.*,/\"datasource\": \"TemporalMetrics\",/g' \\\n> \"/var/lib/grafana/dashboards/default/misc-advanced-visibility-specific-github.json\"\n  \ncurl -skf \\\n--connect-timeout 60 \\\n--max-time 60 \\\n-H \"Accept: application/json\" \\\n-H \"Content-Type: application/json;charset=UTF-8\" \\\n  \"https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/clustermonitoring-kubernetes.json\" \\\n  | sed '/-- .* --/! s/\"datasource\":.*,/\"datasource\": \"TemporalMetrics\",/g' \\\n> \"/var/lib/grafana/dashboards/default/misc-clustermonitoring-kubernetes-github.json\"\n  \ncurl -skf \\\n--connect-timeout 60 \\\n--max-time 60 \\\n-H \"Accept: application/json\" \\\n-H \"Content-Type: application/json;charset=UTF-8\" \\\n  \"https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/frontend-service-specific.json\" \\\n  | sed '/-- .* --/! s/\"datasource\":.*,/\"datasource\": \"TemporalMetrics\",/g' \\\n> \"/var/lib/grafana/dashboards/default/misc-frontend-service-specific-github.json\"\n  \ncurl -skf \\\n--connect-timeout 60 \\\n--max-time 60 \\\n-H \"Accept: application/json\" \\\n-H \"Content-Type: application/json;charset=UTF-8\" \\\n  \"https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/history-service-specific.json\" \\\n  | sed '/-- .* --/! s/\"datasource\":.*,/\"datasource\": \"TemporalMetrics\",/g' \\\n> \"/var/lib/grafana/dashboards/default/misc-history-service-specific-github.json\"\n  \ncurl -skf \\\n--connect-timeout 60 \\\n--max-time 60 \\\n-H \"Accept: application/json\" \\\n-H \"Content-Type: application/json;charset=UTF-8\" \\\n  \"https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/matching-service-specific.json\" \\\n  | sed '/-- .* --/! s/\"datasource\":.*,/\"datasource\": \"TemporalMetrics\",/g' \\\n> \"/var/lib/grafana/dashboards/default/misc-matching-service-specific-github.json\"\n  \ncurl -skf \\\n--connect-timeout 60 \\\n--max-time 60 \\\n-H \"Accept: application/json\" \\\n-H \"Content-Type: application/json;charset=UTF-8\" \\\n  \"https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/worker-service-specific.json\" \\\n  | sed '/-- .* --/! s/\"datasource\":.*,/\"datasource\": \"TemporalMetrics\",/g' \\\n> \"/var/lib/grafana/dashboards/default/misc-worker-service-specific-github.json\"\n  \ncurl -skf \\\n--connect-timeout 60 \\\n--max-time 60 \\\n-H \"Accept: application/json\" \\\n-H \"Content-Type: application/json;charset=UTF-8\" \\\n  \"https://raw.githubusercontent.com/temporalio/dashboards/helm/sdk/sdk-general.json\" \\\n  | sed '/-- .* --/! s/\"datasource\":.*,/\"datasource\": \"TemporalMetrics\",/g' \\\n> \"/var/lib/grafana/dashboards/default/sdk-general-github.json\"\n  \ncurl -skf \\\n--connect-timeout 60 \\\n--max-time 60 \\\n-H \"Accept: application/json\" \\\n-H \"Content-Type: application/json;charset=UTF-8\" \\\n  \"https://raw.githubusercontent.com/temporalio/dashboards/helm/server/server-general.json\" \\\n  | sed '/-- .* --/! s/\"datasource\":.*,/\"datasource\": \"TemporalMetrics\",/g' \\\n> \"/var/lib/grafana/dashboards/default/server-general-github.json\"\n"
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.0.0
    helm.sh/chart: grafana-8.0.2
  name: temporalio-grafana
  namespace: temporal
