apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.29.0
    helm.sh/chart: temporal-0.68.1
  name: temporalio-web
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: temporalio
      app.kubernetes.io/name: temporal
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: temporalio
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.29.0
        helm.sh/chart: temporal-0.68.1
    spec:
      containers:
        - env:
            - name: TEMPORAL_ADDRESS
              value: temporalio-frontend.temporal.svc:7233
            - name: TEMPORAL_UI__CORS__ALLOWED_ORIGINS
              value: '["http://localhost:3000","http://temporal-ui.taila1b08a.ts.net:8080"]'
            - name: TEMPORAL_UI_PORT
              value: "8080"
          image: temporalio/ui:2.40.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: http
          name: temporal-web
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
      serviceAccountName: default
