apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: admintools
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.28.1
    helm.sh/chart: temporal-0.65.0
  name: temporalio-admintools
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: admintools
      app.kubernetes.io/instance: temporalio
      app.kubernetes.io/name: temporal
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admintools
        app.kubernetes.io/instance: temporalio
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.28.1
        helm.sh/chart: temporal-0.65.0
    spec:
      containers:
        - env:
            - name: TEMPORAL_CLI_ADDRESS
              value: temporalio-frontend:7233
            - name: TEMPORAL_ADDRESS
              value: temporalio-frontend:7233
          image: temporalio/admin-tools:1.28.1-tctl-1.18.4-cli-1.4.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - ls
                - /
            initialDelaySeconds: 5
            periodSeconds: 5
          name: admin-tools
      serviceAccountName: default
