apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: matching
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.28.1
    helm.sh/chart: temporal-0.65.0
  name: temporalio-matching
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: matching
      app.kubernetes.io/instance: temporalio
      app.kubernetes.io/name: temporal
  template:
    metadata:
      annotations:
        checksum/config: e1edad743e4efabbb9d2374995f4f00ec40587fb2167000a07d93ff1e885b82f
      labels:
        app.kubernetes.io/component: matching
        app.kubernetes.io/instance: temporalio
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.28.1
        helm.sh/chart: temporal-0.65.0
    spec:
      containers:
        - env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICES
              value: matching
            - name: TEMPORAL_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-default-store
            - name: TEMPORAL_VISIBILITY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-visibility-store
          image: temporalio/server:1.28.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 150
            tcpSocket:
              port: rpc
          name: temporal-matching
          ports:
            - containerPort: 7235
              name: rpc
              protocol: TCP
            - containerPort: 6935
              name: membership
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/temporal/config/config_template.yaml
              name: config
              subPath: config_template.yaml
            - mountPath: /etc/temporal/dynamic_config
              name: dynamic-config
      initContainers:
        - command:
            - sh
            - -c
            - until cqlsh temporalio-cassandra.temporal 9042 -e "SHOW VERSION"; do echo waiting for cassandra to start; sleep 1; done;
          image: cassandra:3.11.3
          imagePullPolicy: IfNotPresent
          name: check-cassandra
        - command:
            - sh
            - -c
            - until cqlsh temporalio-cassandra.temporal 9042 -e "SELECT keyspace_name FROM system_schema.keyspaces" | grep temporal$; do echo waiting for default keyspace to become ready; sleep 1; done;
          image: cassandra:3.11.3
          imagePullPolicy: IfNotPresent
          name: check-cassandra-temporal-schema
        - command:
            - sh
            - -c
            - until curl --silent --fail --user "$ES_USER:$ES_PWD" $ES_SCHEME://$ES_HOST:$ES_PORT/$ES_VISIBILITY_INDEX 2>&1 > /dev/null; do echo waiting for elasticsearch index to become ready; sleep 1; done;
          env:
            - name: ES_SCHEME
              value: http
            - name: ES_HOST
              value: elasticsearch-master-headless
            - name: ES_PORT
              value: "9200"
            - name: ES_USER
              value: ""
            - name: ES_PWD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: temporalio-visibility-store
            - name: ES_VERSION
              value: v7
            - name: ES_VISIBILITY_INDEX
              value: temporal_visibility_v1_dev
          image: temporalio/admin-tools:1.28.1-tctl-1.18.4-cli-1.4.1
          imagePullPolicy: IfNotPresent
          name: check-elasticsearch-index
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: default
      volumes:
        - configMap:
            name: temporalio-config
          name: config
        - configMap:
            items:
              - key: dynamic_config.yaml
                path: dynamic_config.yaml
            name: temporalio-dynamic-config
          name: dynamic-config
