apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: hook-succeeded
  name: temporalio-xlbiw-test
  namespace: temporal
spec:
  containers:
    - command:
        - sh
        - -c
        - |
          #!/usr/bin/env bash -e
          curl -XGET --fail 'elasticsearch-master:9200/_cluster/health?wait_for_status=green&timeout=1s'
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.29
      imagePullPolicy: IfNotPresent
      name: temporalio-axpbz-test
  restartPolicy: Never
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
