apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-master-pdb
  namespace: temporal
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: elasticsearch-master
