apiVersion: v1
data:
  password: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.28.1
    helm.sh/chart: temporal-0.65.0
  name: temporalio-visibility-store
  namespace: temporal
type: Opaque
