apiVersion: v1
data:
  admin-password: SVNjdkRyMzI2QndBZFBzek5iamtrS2tsaEZwTDBxalR3N0NhNFM5cw==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.0.0
    helm.sh/chart: grafana-8.0.2
  name: temporalio-grafana
  namespace: temporal
type: Opaque
