apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
  name: temporal-frontend-tailscale
  namespace: temporal
spec:
  ports:
    - name: grpc
      port: 7233
      protocol: TCP
      targetPort: 7233
    - name: x
      port: 8233
      protocol: TCP
      targetPort: 8233
    - name: ui
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/name: temporal
