apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
    chart: cassandra-0.14.3
    heritage: Helm
    release: temporalio
  name: temporalio-cassandra
  namespace: temporal
spec:
  clusterIP: None
  ports:
    - name: intra
      port: 7000
      targetPort: 7000
    - name: tls
      port: 7001
      targetPort: 7001
    - name: jmx
      port: 7199
      targetPort: 7199
    - name: cql
      port: 9042
      targetPort: 9042
    - name: thrift
      port: 9160
      targetPort: 9160
  selector:
    app: cassandra
    release: temporalio
  type: ClusterIP
