apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: v1.8.0
    helm.sh/chart: prometheus-pushgateway-2.13.0
  name: temporalio-prometheus-pushgateway
  namespace: temporal
