apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: pushgateway
  labels:
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: v1.8.0
    helm.sh/chart: prometheus-pushgateway-2.13.0
  name: temporalio-prometheus-pushgateway
  namespace: temporal
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app.kubernetes.io/instance: temporalio
    app.kubernetes.io/name: prometheus-pushgateway
  type: ClusterIP
