apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: n8n
    app.kubernetes.io/version: 1.109.1
    helm.sh/chart: n8n-1.0.14
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: n8n
      app.kubernetes.io/name: n8n
      app.kubernetes.io/type: master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: 4acebf764c1d70f011dd9ce5c46e61c8c1d51e69760dcaf409a6e44cb5ea17c8
      labels:
        app.kubernetes.io/instance: n8n
        app.kubernetes.io/name: n8n
        app.kubernetes.io/type: master
    spec:
      containers:
        - env: []
          image: n8nio/n8n:1.109.1
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          name: n8n
          ports:
            - containerPort: 5678
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources: {}
          securityContext: {}
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: data
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: n8n
      volumes:
        - emptyDir: {}
          name: data
