apiVersion: v1
data:
  postgres-password: ZXJkblhmT3VqdA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgresql-16.7.26
  name: n8n-postgresql
  namespace: n8n
type: Opaque
