apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
  name: tailscale
  namespace: n8n
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5678
  selector:
    app: n8n
